import random

list1 = ["stupid",
  "shitfaced",
  "inbred",
  "dumbass",
  "fucking",
  "horse-riding",
  "unbelievable",
  "mother-of-a",
  "whiteclaw-drinking",
  "cousin-fucking",
  "sideburn-having",
  "beak-having",
  "malnourished",
  "homeless",
  "orphaned",
  "unloved",
  "soft",
  "homeless",
  "minimum-wage",
  "unhappy"]

list2 = ["disrespecful",
  "douchebag",
  "gooberfaced",
  "bitchy",
  "biggotted",
  "wankfaced",
  "chodemouthed",
  "fartfaced",
  "nutmouthed",
  "sister-fucking",
  "child-fucking",
  "butteraced",
  "red-necked",
  "fat",
  "pencil-dicked",
  "poverty-ridden",
  "bronze-leveled",
  "burger-flipping",
  "clap-having",
  "lip-packing"]

list3 = ["wine-drinker",
  "shitter",
  "tiddy",
  "fuck",
  "fucker",
  "taint",
  "dunce",
  "neanderthawl",
  "mongaloid",
  "fuckhead",
  "dumpster-cunt",
  "ape",
  "sally",
  "alter-boy",
  "blue-gum",
  "weeaboo",
  "skinny-penis",
  "guido",
  "choch",
  "heffer",
  "shitbird",
  "headass",
  "liberal",
  "female",
  "canook",
  "chad",
  "alter-boy",
  "chud"]

insult=("you "+list1[random.randint(0,18)]+", "+list2[random.randint(0,18)]+", "+list3[random.randint(0,26)])
